//
// Created by yangguo on 11/25/22.
//

#ifndef TRAJ_BLOCK_FORMAT_CONFIG_H
#define TRAJ_BLOCK_FORMAT_CONFIG_H

#define SPLIT_SEGMENT_NUM 12
#define TRAJ_BLOCK_SIZE 4096    // 4 KB
#define INDEX_BLOCK_SIZE 4096
#define WITH_RESULT true

#endif //TRAJ_BLOCK_FORMAT_CONFIG_H
